services:
  docktest:
    image: docktest
    build: .
    # user: "1000:1000"
    # image: timothyjmiller/cloudflare-ddns:latest
    container_name: docktest
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    command: --interval 30
    environment:
      # - PUID=1000
      # - PGID=1000
      - CF_DDNS_API_TOKEN=THISISMYSECRETTOKENBIGGERBETTER
    volumes:
      - ./config-example.json:/config.json:ro
    restart: unless-stopped