name: Publish Docker Image to Registries

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      # - name: Cache Docker layers
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ runner.temp }}/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-          
          
      - name: Get Repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
            # type=sha,format=short
        with:
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=true
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}
            ${{ env.REGISTRY }}/${{ github.repository }}
  
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
          
      - name: Build and push images
        id: push
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          file: docker/Dockerfile
          push: true
          provenance: false
          sbom: false
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # ,linux/386,linux/arm/v7
          # linux/amd64,linux/arm64,linux/386,linux/arm/v6,linux/arm/v7,linux/riscv64
          # cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          # cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

      # - name: Generate SBOM
      #   uses: anchore/sbom-action@v0
      #   with:
      #     image: ${{ env.REGISTRY }}/${{ github.repository }}:latest
      #     format: 'spdx-json'
      #     output-file: 'sbom.spdx.json'
      # - name: Attest
      #   uses: actions/attest-sbom@v3
      #   id: attest
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ github.repository }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     sbom-path: 'sbom.spdx.json'
      #     push-to-registry: true
          
      # - name: Generate artifact attestation for registry
      #   uses: actions/attest-build-provenance@v3
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ github.repository }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
          
      # - name: Generate artifact attestation for docker.io
      #   uses: actions/attest-build-provenance@v3
      #   with:
      #     subject-name: docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
      
      - name: Attest for docker.io
        uses: actions/attest@v3
        id: attest
        with:
          subject-name: index.docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          predicate-type: 'https://slsa.dev/provenance/v1'
          predicate: '{}'
          push-to-registry: true
          
      # - name: Generate artifact attestation for ghcr.io
      #   uses: actions/attest-build-provenance@v3
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ github.repository }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
  
      # Temp fix workaround https://docs.docker.com/build/ci/github-actions/cache/#local-cache
      # - name: Update Buildx cache
      #   run: |
      #     rm -rf ${{ runner.temp }}/.buildx-cache
      #     mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
      
      
          

  
      # # 9. Build and push prod image
      # - name: Build and push production image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: Dockerfile
      #     push: true
      #     platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v6,linux/arm/v7,linux/riscv64
      #     tags: |
      #       ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
      #       ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
      #     cache-from: type=local,src=/tmp/.buildx-cache