name: Auto Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # creating tags and releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        # with:
        #   fetch-depth: 0  # for comparing commits

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14' # same version with docker python:alpine
      
      - name: Get Repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        
      - name: Create zipapp
        run: |
          mkdir dist
          python -m zipapp src -o dist/${{ env.REPOSITORY_NAME }}.pyz -c -m "main:main"
          chmod +x dist/${{ env.REPOSITORY_NAME }}.pyz

      - name: Copy additional files
        run: |
          cp requirements.txt dist/ || true
          cp config-example.json dist/ || true
          cp systemd/install.sh dist/ || true
          echo "Copied additional files"

      - name: Create tar.gz installation package
        run: |
          tar -cvzf ${{ env.REPOSITORY_NAME }}-install.tar.gz -C dist .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          body: |
            Automated release ${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}
          files: |
            ${{ env.REPOSITORY_NAME }}-install.tar.gz
            README.md
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
