name: Auto Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # creating tags and releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        # with:
        #   fetch-depth: 0  # for comparing commits

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14' # same version with docker python:alpine

      - name: Create zipapp
        run: |
          mkdir dist
          python -m zipapp src -o dist/docktest.pyz -c -m "main:main"
          echo "Built dist/docktest.pyz"

      - name: Copy additional files
        run: |
          cp requirements.txt dist/ || true
          cp config-example.json dist/ || true
          cp systemd/install.sh dist/ || true
          echo "Copied additional files"

      - name: Create tar.gz installation package
        run: |
          tar -cvzf ${{ github.repository }}-install.tar.gz dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          body: |
            Automated release ${{ github.repository }}-${{ github.ref }}
          files: |
            ${{ github.repository }}.tar.gz
            README.md
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
